src/opentelemetry/lightstep/configuration.py
=> Handle 32, 84 and 104 character long tokens

src/opentelemetry/lightstep/configuration.py, tests/test_configuration.py
=> Pass right metadata

src/opentelemetry/lightstep/configuration.py
=> Update environment variable names

src/opentelemetry/lightstep/configuration.py
=> Use logging.ERROR as default logging level

.github/workflows/build.yml
=> Use right interpreter when running Nox

.github/workflows/build.yml, pytest.ini, src/opentelemetry/launcher/configuration.py, tests/test_configuration.py
=> Set log levels with strings

tests/test_configuration.py
=> Use right logger

setup.cfg, src/opentelemetry/launcher/configuration.py
=> Configure with instrumentation

setup.cfg, src/opentelemetry/launcher/tracer.py
=> Update OTLP dependency

examples/client.py, examples/server.py
Adding an example of setting/getting correlations. Updating examples to use new instrumentation packages.
=> updating examples

tests/test_configuration.py
=> Stop tests from running forever

setup.cfg, src/opentelemetry/launcher/configuration.py, tests/test_configuration.py
=> Update to latest version of opentelemetry

README.md, src/opentelemetry/launcher/configuration.py, tests/test_configuration.py
=> Do not set unknown service version

CHANGELOG.md, src/opentelemetry/launcher/configuration.py, tests/test_configuration.py
=> Set host.name in Resource attributes

CHANGELOG.md, README.md, examples/client.py, examples/server.py, noxfile.py, setup.cfg, src/opentelemetry/launcher/configuration.py, src/opentelemetry/launcher/metrics.py, src/opentelemetry/launcher/version.py, tests/test_configuration.py
=> Add metrics exporter and configuration for SystemMetrics

README.md
=> chore: prepare 0.15b0 release

src/opentelemetry/launcher/configuration.py, tests/test_configuration.py
=> Add metrics_enabled option

CHANGELOG.md, examples/client.py, setup.cfg, src/opentelemetry/launcher/configuration.py, src/opentelemetry/launcher/version.py
=> Preparing 0.17b0 release

CHANGELOG.md, README.md, setup.cfg, src/opentelemetry/launcher/version.py
=> chore: Preparing 1.0.0 release

setup.cfg
Fixes #82
Please review first.
=> Update dependency versions

requirements-test.txt, src/opentelemetry/launcher/configuration.py, tests/test_configuration.py
Fixes #94
FIXME Merge after the ot-trace package has been released and after
fixing back the versions in requirements.txt
=> Load propagators from entry points

CHANGELOG.md, src/opentelemetry/launcher/version.py
=> Release 1.2.0

RELEASING.md
=> Add more releasing instructions

RELEASING.md, examples/client.py, examples/server.py, noxfile.py, src/opentelemetry/launcher/configuration.py, tests/test_example.py
=> Enhance example test

README.md, src/opentelemetry/launcher/configuration.py, tests/test_configuration.py
=> Add support for OTEL_SERVICE_NAME

.github/workflows/build.yml, .pylintrc, CHANGELOG.md, noxfile.py, requirements-test.txt, setup.cfg, src/opentelemetry/launcher/configuration.py
=> Remove support for 3.6

setup.cfg, src/opentelemetry/launcher/version.py
=> Add missing release changes

CHANGELOG.md, src/opentelemetry/launcher/version.py
=> Release 1.11.0

src/opentelemetry/launcher/configuration.py, tests/test_configuration.py
=> Add support for OTEL_METRIC_EXPORT_INTERVAL

CHANGELOG.md, src/opentelemetry/launcher/version.py
=> Release 1.15.0
